name: pull-and-push

on:
  workflow_dispatch:  # 수동으로 실행할 수 있는 옵션

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: source kr2 public
        uses: docker/login-action@v1
        with:
          registry: cloudtech-main.kr-central-2.kcr.dev # source
          username: 6af26e4c6f5945dd88c39193295d1af3
          password: vUEGdWRCUGH46pzLZHmK2BvTp8UXzAKBypq_q-abaxUBWtl50vtOsA1nbaPNUknWk3ikfDDl1ob8Jn08VrY2gg

      - name: source image pull
        run: |
          docker pull cloudtech-main.kr-central-2.kcr.dev/justin/clue-client:develop # clue-client 이미지 가져오기
          
      - name: Configure AWS credentials
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | aws configure set aws_access_key_id --profile default
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | aws configure set aws_secret_access_key --profile default
          echo "us-east-1" | aws configure set region --profile default  # 필요한 리전으로 변경

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com


      - name: 대상 레지스트리용 이미지 태그 변경
        run: |
          docker tag cloudtech-main.kr-central-2.kcr.dev/justin/clue-client:develop cloudtech.kr-gov-central-1.kcr.dev/cloudtech-gov/clue-client:develop # 이미지 태그 변경

      - name: 대상 레지스트리에 Docker 이미지 푸시
        run: |
          docker push cloudtech.kr-gov-central-1.kcr.dev/cloudtech-gov/clue-client:develop # 대상 레지스트리에 이미지 푸시
