name: Push to KCR

on:
  workflow_dispatch:  # 수동으로 실행할 수 있는 옵션

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Source Container Registry
        uses: docker/login-action@v1
        with:
          registry: source-registry-url # 소스 레지스트리 URL
          username: ${{ secrets.SOURCE_REGISTRY_USERNAME }} # 소스 레지스트리 사용자 이름
          password: ${{ secrets.SOURCE_REGISTRY_PASSWORD }} # 소스 레지스트리 비밀번호

      - name: Pull image from Source Registry
        run: |
          docker pull source-registry-url/path/to/image:tag # 소스 레지스트리에서 이미지 가져오기

      - name: Log in to Destination Container Registry
        uses: docker/login-action@v1
        with:
          registry: dev-hrs.kr-gov-central-1.kcr.dev # 대상 레지스트리 URL
          username: ${{ secrets.KCR_USERNAME }} # GitHub Secrets에 저장된 대상 레지스트리 사용자 이름
          password: ${{ secrets.KCR_PASSWORD }} # GitHub Secrets에 저장된 대상 레지스트리 비밀번호

      - name: Tag the image for Destination Registry
        run: |
          docker tag source-registry-url/path/to/image:tag dev-hrs.kr-gov-central-1.kcr.dev/dev-hrs-app/clue-client:develop # 이미지 태그 변경

      - name: Push Docker image to Destination Registry
        run: |
          docker push dev-hrs.kr-gov-central-1.kcr.dev/dev-hrs-app/clue-client:develop # 대상 레지스트리에 이미지 푸시
